@ Super Scribblenauts (EU) ARM9 function ARM <-> Thumb wrappers
@ Generated by https://github.com/XorTroll/super-scribblenauts-re at February 19, 2025 06:40:45 PM */

.macro BEGIN_ASM_FN name section=text
    .section .\section\().\name\(), "ax", %progbits
    .global \name
    .type \name, %function
    .align 2
\name:
.endm

BEGIN_ASM_FN Svc_Delay
    ldr r12, =Svc_Delay_from_thumb
    orr r12, r12, #1
    bx r12

