site_name: Super Scribblenauts (EU) documentation
site_description: Super Scribblenauts (EU) reverse-enginnering, documented here
site_author: XorTroll
site_url: https://xortroll.github.io/super-scribblenauts-re/

repo_name: super-scribblenauts-re
repo_url: https://github.com/XorTroll/super-scribblenauts-re

nav:
  - Home: index.md
  - Languages: lang.md
  - Filesystem: fs.md
  - Game file formats:
    - Text list file: game/text-list.md
    - Font file: game/font.md
    - Sprite files: game/sprite.md
    - GUI files: game/gui.md
  - Objectnaut:
    - Objectnaut: objnaut/objnaut.md
    - Dictionary files: objnaut/dictionary.md
    - Object files: objnaut/object.md
    - Object texture files: objnaut/texture.md
    - Adjective files: objnaut/adjective.md
    - Animation files: objnaut/animation.md
    - Attack files: objnaut/attack.md
  - Objects:
    - Object list (en): objgen-en/index.html

theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
